### ISSUE TITLE
[DUPLICATE] Add GitHub Actions CI Badge to README.md

### ISSUE THREAD

**Issue by gary1209** [CSCI-GA-2820-FA23-003/shopcarts#61] opened 2023-11-07 03:39 UTC
**As a** developer
**I need** to add a GitHub Actions CI badge to the README.md file
**So that** everyone can easily see whether the build is working or broken.
 ### Details and Assumptions
 * The GitHub Actions workflow for running unit tests has been set up successfully.
 * The GitHub Actions CI badge URL is available.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the GitHub repository for the project
When I open the README.md file
Then I should see a GitHub Actions CI badge indicating the build status.
```

**Comment by sahishnu** [comment] 2023-11-07 21:28
This is a duplicate of https://github.com/CSCI-GA-2820-FA23-003/shopcarts/issues/53

**Closed by sahishnu** 2023-11-07 21:28 UTC
Labels: duplicate
